### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by tommoor** [sqwiggle/sqwiggle-blog#2]
Anyone against me making this repository public? No secrets here right? 

@ericbieller @mattboyd

**Comment by mattboyd** [comment]
No secrets on our end, but this hasn't been updated in a while. Not sure
how to push to two different repos.

**Comment by tommoor** [comment]
`git push origin master` will update github

On Tue, Nov 5, 2013 at 4:12 PM, mattboyd notifications@github.com wrote:

> No secrets on our end, but this hasn't been updated in a while. Not sure
> how to push to two different repos.
> 
> On Tue, Nov 5, 2013 at 4:00 AM, Tom Moor notifications@github.com
> wrote:
> 
> > Anyone against me making this repository public? No secrets here right?
> > 
> > @ericbieller https://github.com/ericbieller @mattboyd<
> > https://github.com/mattboyd>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sqwiggle/sqwiggle-blog/issues/2>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sqwiggle/sqwiggle-blog/issues/2#issuecomment-27786264
> .

## 

Tom Moor

http://tommoor.com
http://twitter.com/tommoor

**Comment by mattboyd** [comment]
errors out.

" ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:
sqwiggle/sqwiggle-blog.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details."

**Comment by tommoor** [comment]
done.
