### ISSUE TITLE
Tweak blog popup CTA design

### ISSUE THREAD

**Issue by ericbieller** [sqwiggle/sqwiggle-blog#29]
Let's try for something closer to this.

![screen shot 2014-08-14 at 11 09 37 am](https://cloud.githubusercontent.com/assets/740552/3924536/35b9e6ce-23de-11e4-9ce5-f02c4206bec4.png)

**Comment by ericbieller** [comment]
@mattboyd thing you'll be able to prioritize this soon?

**Comment by mattboyd** [comment]
It's been on my list for 2 days, just haven't got to it yet. Hopefully will
today.
